package com.example.thenotesapp.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

@Entity(tableName = "notes")
@Parcelize
data class Note(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, // Automatically generated by Room
    val noteTitle: String,
    val noteDesc: String,
    val isPinned: Boolean = false,
    val isLocked: Boolean = false,
    val pinCode: String? = null // Optional PIN for locked notes
) : Parcelable
